name: brandon
favicon: null
layout_spectrum: 0.8056826286483556
typography_spectrum: 0.4168717332649976
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#FF6700'
    - '#EBEBEB'
    - '#C0C0C0'
    - '#3A6EA5'
    - '#004E98'
  brandStrength: 0.3898705360479653
  lightness: 0.327644455479458
  saturation: 0.39730628090910614
  rhythmicContrast: 0.2845647919457406
purpose: []
